// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.unnie.domain;

import com.sut.unnie.domain.Salt;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Salt_Roo_Configurable {
    
    declare @type: Salt: @Configurable;
    
}
